/**
 * Runtime blog store: load index (meta + chunks) from disk (data/chunks.json).
 * Supports wrapper format { meta, chunks } and legacy array-of-chunks.
 * On Vercel, the file must be present in the repo (generated by ingest and committed).
 */

import path from "path";
import fs from "fs";
import type { BlogChunk, PostIndexEntry } from "./csv-store";
import { retrieve, type ChunkWithScore } from "./csv-store";

const DATA_DIR = path.join(process.cwd(), "data");
const CHUNKS_FILE = path.join(DATA_DIR, "chunks.json");

export interface IndexMeta {
  totalPosts: number;
  totalChunks: number;
  lastIngestedAt: string;
  postsIndex: PostIndexEntry[];
}

interface BlogIndex {
  meta: IndexMeta;
  chunks: BlogChunk[];
}

let cachedIndex: BlogIndex | null = null;

function parseIndex(raw: string): BlogIndex {
  const data = JSON.parse(raw);
  if (data && typeof data.meta === "object" && Array.isArray(data.chunks)) {
    return {
      meta: {
        totalPosts: Number(data.meta.totalPosts) || 0,
        totalChunks: Number(data.meta.totalChunks) || 0,
        lastIngestedAt: String(data.meta.lastIngestedAt ?? ""),
        postsIndex: Array.isArray(data.meta.postsIndex) ? data.meta.postsIndex : [],
      },
      chunks: data.chunks,
    };
  }
  if (Array.isArray(data)) {
    const slugs = new Set<string>();
    data.forEach((c: BlogChunk) => c.slug && slugs.add(c.slug));
    return {
      meta: {
        totalPosts: slugs.size,
        totalChunks: data.length,
        lastIngestedAt: "",
        postsIndex: [],
      },
      chunks: data,
    };
  }
  return {
    meta: { totalPosts: 0, totalChunks: 0, lastIngestedAt: "", postsIndex: [] },
    chunks: [],
  };
}

export function getChunksFilePath(): string {
  return CHUNKS_FILE;
}

/** Load index (meta + chunks). Returns empty meta and chunks if file missing or invalid. */
function loadIndex(): BlogIndex {
  if (cachedIndex) return cachedIndex;
  try {
    const raw = fs.readFileSync(CHUNKS_FILE, "utf-8");
    cachedIndex = parseIndex(raw);
    return cachedIndex;
  } catch {
    cachedIndex = {
      meta: { totalPosts: 0, totalChunks: 0, lastIngestedAt: "", postsIndex: [] },
      chunks: [],
    };
    return cachedIndex;
  }
}

/** Get dataset metadata (totalPosts, totalChunks, lastIngestedAt, postsIndex). */
export function getMeta(): IndexMeta {
  return loadIndex().meta;
}

/** Load chunks only. Returns [] if file missing or invalid. */
export function loadChunks(): BlogChunk[] {
  return loadIndex().chunks;
}

/** Retrieve top chunks for a query. */
export function getRelevantChunks(query: string, topK = 5): ChunkWithScore[] {
  const chunks = loadChunks();
  return retrieve(chunks, query, topK);
}

/** Clear in-memory cache (e.g. after re-ingest in dev). */
export function clearChunkCache(): void {
  cachedIndex = null;
}
