/**
 * Runtime blog store: load index (meta + chunks) from disk (data/chunks.json).
 * Supports wrapper format { meta, chunks } and legacy array-of-chunks.
 * When meta.hasEmbeddings and chunks have .embedding, uses semantic search (Gemini); else keyword (TF*IDF).
 * On Vercel, the file must be present in the repo (generated by ingest and committed).
 */

import path from "path";
import fs from "fs";
import type { BlogChunk, PostIndexEntry } from "./csv-store";
import { retrieve, retrieveByEmbedding, type ChunkWithScore } from "./csv-store";
import { embedForQuery } from "./embeddings";

const DATA_DIR = path.join(process.cwd(), "data");
const CHUNKS_FILE = path.join(DATA_DIR, "chunks.json");

export interface IndexMeta {
  totalPosts: number;
  totalChunks: number;
  lastIngestedAt: string;
  postsIndex: PostIndexEntry[];
  /** True when chunks have embeddings (semantic search). */
  hasEmbeddings?: boolean;
}

interface BlogIndex {
  meta: IndexMeta;
  chunks: BlogChunk[];
}

let cachedIndex: BlogIndex | null = null;

function parseIndex(raw: string): BlogIndex {
  const data = JSON.parse(raw);
  if (data && typeof data.meta === "object" && Array.isArray(data.chunks)) {
    return {
      meta: {
        totalPosts: Number(data.meta.totalPosts) || 0,
        totalChunks: Number(data.meta.totalChunks) || 0,
        lastIngestedAt: String(data.meta.lastIngestedAt ?? ""),
        postsIndex: Array.isArray(data.meta.postsIndex) ? data.meta.postsIndex : [],
        hasEmbeddings: data.meta.hasEmbeddings === true,
      },
      chunks: data.chunks,
    };
  }
  if (Array.isArray(data)) {
    const slugs = new Set<string>();
    data.forEach((c: BlogChunk) => c.slug && slugs.add(c.slug));
    return {
      meta: {
        totalPosts: slugs.size,
        totalChunks: data.length,
        lastIngestedAt: "",
        postsIndex: [],
        hasEmbeddings: false,
      },
      chunks: data,
    };
  }
  return {
    meta: { totalPosts: 0, totalChunks: 0, lastIngestedAt: "", postsIndex: [], hasEmbeddings: false },
    chunks: [],
  };
}

export function getChunksFilePath(): string {
  return CHUNKS_FILE;
}

/** Load index (meta + chunks). Returns empty meta and chunks if file missing or invalid. */
function loadIndex(): BlogIndex {
  if (cachedIndex) return cachedIndex;
  try {
    const raw = fs.readFileSync(CHUNKS_FILE, "utf-8");
    cachedIndex = parseIndex(raw);
    return cachedIndex;
  } catch {
    cachedIndex = {
      meta: { totalPosts: 0, totalChunks: 0, lastIngestedAt: "", postsIndex: [] },
      chunks: [],
    };
    return cachedIndex;
  }
}

/** Get dataset metadata (totalPosts, totalChunks, lastIngestedAt, postsIndex). */
export function getMeta(): IndexMeta {
  return loadIndex().meta;
}

/** Load chunks only. Returns [] if file missing or invalid. */
export function loadChunks(): BlogChunk[] {
  return loadIndex().chunks;
}

/** Retrieve top chunks for a query. Uses semantic search when embeddings exist, else keyword (TF*IDF). */
export async function getRelevantChunks(query: string, topK = 5): Promise<ChunkWithScore[]> {
  const index = loadIndex();
  const chunks = index.chunks;
  const useSemantic =
    index.meta.hasEmbeddings === true &&
    chunks.length > 0 &&
    Array.isArray((chunks[0] as BlogChunk).embedding);
  if (useSemantic) {
    try {
      const queryEmbedding = await embedForQuery(query);
      const byEmbedding = retrieveByEmbedding(chunks, queryEmbedding, topK);
      if (byEmbedding.length > 0) return byEmbedding;
    } catch (e) {
      console.warn("Semantic search failed, falling back to keyword:", e);
    }
  }
  return retrieve(chunks, query, topK);
}

/** Get all chunks for a given post (by CSV row order index). Used for "first blog" / "last blog" so the model can describe content. */
export function getChunksForPost(postIndex: number): ChunkWithScore[] {
  const chunks = loadChunks();
  return chunks
    .filter((c) => c.postIndex === postIndex)
    .map((c) => ({ ...c, score: 1 }));
}

/** Clear in-memory cache (e.g. after re-ingest in dev). */
export function clearChunkCache(): void {
  cachedIndex = null;
}
